# Generated by Django 5.0.6 on 2024-06-13 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionusuario', '0003_grupo_trabajadores_delete_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ART',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_firmas', models.PositiveIntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionusuario.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionusuario.art')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
